default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: ubuntu
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: audit_planning_development

# production:
#   <<: *default
#   database: audit_planning_development

# test:
#   <<: *default
#   database: audit_planning_test

# production:
#   <<: *default
#   database: audit_planning_production
#   username: audit_planning
#   password: <%= ENV['AUDIT_PLANNING_DATABASE_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 15
  password: 
  database: audit_planning_production